# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r:
  - release
  - devel

os:
  - linux
  - osx

compiler:
  - clang

matrix:
  fast_finish: true
  allow_failures:
    - r: devel
    - os: osx

before_install:
  - export TZ=US/Central

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    - k.vasilopoulo@gmail.com
    on_success: never
    on_failure: always
